# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://patrickjbritton.github.io/
baseurl: http://thegreatbritton.com/
title: Patrick Britton
author: Patrick Britton
description: Personal blog and resume
avatar: profile.png
email: patrick@britton86.com
github: pjbritton # username
twitter: 
linkedin: 
stackoverflow:   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus: 
google_analytics: 

# needed for travis-ci build
exclude: [vendor]
